include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = WeChatEnhanceSettings
WeChatEnhanceSettings_FILES = ../Preferences/Settings.xm
WeChatEnhanceSettings_INSTALL_PATH = /Library/PreferenceBundles
WeChatEnhanceSettings_FRAMEWORKS = UIKit
WeChatEnhanceSettings_PRIVATE_FRAMEWORKS = Preferences
WeChatEnhanceSettings_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
